version: 0.2

env:
  variables:
    IMAGE_NAME: helloworld
    AWS_ACCOUNT_ID: 851940729109

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_URI}:${IMAGE_TAG}
      - echo Building task definitions...
      - printf '[{"name":"service","imageUri":"%s"}]' ${IMAGE_URI}:${IMAGE_TAG} > imagedef.json

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${IMAGE_URI}:${IMAGE_TAG}

artifacts:
  files:
    - imagedef.json
